# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 22:50
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import shop.util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0002_auto_20200526_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('isbn', models.CharField(max_length=255)),
                ('number_of_pages', models.IntegerField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='CompactDiscProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('number_of_tracks', models.IntegerField()),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('baseproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BaseProduct')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('shop.product',),
        ),
    ]
