# Generated by Django 2.2.12 on 2020-05-28 20:18

from decimal import Decimal
from django.db import migrations, models
import shop.util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unit_price', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30)),
            ],
        ),
    ]
