# Generated by Django 2.2.12 on 2020-05-28 20:18

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import shop.util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(10, 'Processing'), (20, 'Confirming'), (30, 'Confirmed'), (40, 'Completed'), (50, 'Shipped'), (60, 'Canceled')], default=10, verbose_name='Status')),
                ('order_subtotal', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Order subtotal')),
                ('order_total', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Order Total')),
                ('shipping_address_text', models.TextField(blank=True, null=True, verbose_name='Shipping address')),
                ('billing_address_text', models.TextField(blank=True, null=True, verbose_name='Billing address')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('cart_pk', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cart primary key')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('unit_price', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Unit price')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_shop.product_set+', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('isbn', models.CharField(max_length=255)),
                ('number_of_pages', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='CompactDiscProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('number_of_tracks', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
            bases=('shop.product',),
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Amount')),
                ('transaction_id', models.CharField(help_text="The transaction processor's reference", max_length=255, verbose_name='Transaction ID')),
                ('payment_method', models.CharField(help_text='The payment backend used to process the purchase', max_length=255, verbose_name='Payment method')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order payment',
                'verbose_name_plural': 'Order payments',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_reference', models.CharField(max_length=255, verbose_name='Product reference')),
                ('product_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Product name')),
                ('unit_price', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Unit price')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('line_subtotal', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Line subtotal')),
                ('line_total', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Line total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Order', verbose_name='Order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.Product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Extra info')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='shop.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order extra info',
                'verbose_name_plural': 'Order extra info',
            },
        ),
        migrations.CreateModel(
            name='ExtraOrderPriceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('value', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Amount')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Serialized extra data')),
                ('is_shipping', models.BooleanField(default=False, editable=False, verbose_name='Is shipping')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Extra order price field',
                'verbose_name_plural': 'Extra order price fields',
            },
        ),
        migrations.CreateModel(
            name='ExtraOrderItemPriceField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('value', shop.util.fields.CurrencyField(decimal_places=2, default=Decimal('0.0'), max_digits=30, verbose_name='Amount')),
                ('data', jsonfield.fields.JSONField(blank=True, null=True, verbose_name='Serialized extra data')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.OrderItem', verbose_name='Order item')),
            ],
            options={
                'verbose_name': 'Extra order item price field',
                'verbose_name_plural': 'Extra order item price fields',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.Cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Product')),
            ],
            options={
                'verbose_name': 'Cart item',
                'verbose_name_plural': 'Cart items',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.Product')),
                ('baseproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.BaseProduct')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'abstract': False,
            },
            bases=('shop.product',),
        ),
    ]
