# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-26 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user_billing',
        ),
        migrations.RemoveField(
            model_name='address',
            name='user_shipping',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
